In [2]:
import numpy as np

1. Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [10]:
array = None

### start your implementation here ###
# array = ... 
### end your implementation here ###
print("An array of 10 zeros:")
print(array)

### start your implementation here ###
# array = ... 
### end your implementation here ###
print("\nAn array of 10 ones:")
print(array)

### start your implementation here ###
# array = ... 
### end your implementation here ###
print("\nAn array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


2. Write a NumPy program to create an array of the integers from 30 to 70.

In [9]:
array = None

### start your implementation here ###
# array = ... 
### end your implementation here ###
print("Array of the integers from 30 to 70")
print(array)

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


3. Write a NumPy program to create a 3x3 identity matrix.

In [11]:
array_2D = None

### start your implementation here ###
# array = ... 
### end your implementation here ###
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [2]:
x = None

### start your implementation here ###
# x = ...
# x[...] = ... 
### end your implementation here ###
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [3]:
x = None

### start your implementation here ###
# x = ...
# x[...] = ... 
# x[...] = ...
### end your implementation here ###
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


6. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [7]:
nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last rows of the said array:")
### start your implementation here ###
# nums[...] = ...
### end your implementation here ###
print(nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


7. Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive.

In [8]:
x = None

### start your implementation here ###
# x = ...
# x[...] = ... 
### end your implementation here ###
print(x)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


8. Write a NumPy program to replace all elements of NumPy array that are greater than 0.5 to be 0.5.

In [10]:
x = np.array([[ 0.42436315, 0.48558583, 0.32924763], [ 0.7439979,0.58220701,0.38213418], [ 0.5097581,0.34528799,0.1563123 ]])
print("Original array:")
print(x)
print("Replace all elements of the said array with .5 which are greater than .5")
### start your implementation here ###
# x[...] = ... 
### end your implementation here ###
print(x)

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


9. Write a NumPy program to stack arrays in sequence horizontally (column wise).

In [13]:
print("\nOriginal arrays:")
x = np.arange(9).reshape(3,3)
y = x*3
print("Array-1")
print(x)
print("Array-2")
print(y)

new_array = None
### start your implementation here ###
# new_array = ... 
### end your implementation here ###
print("\nStack arrays in sequence horizontally:")
print(new_array)


Original arrays:
Array-1
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array-2
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]

Stack arrays in sequence horizontally:
[[ 0  1  2  0  3  6]
 [ 3  4  5  9 12 15]
 [ 6  7  8 18 21 24]]


10. Write a NumPy program to stack arrays in sequence vertically.

In [4]:
print("\nOriginal arrays:")
x = np.arange(9).reshape(3,3)
y = x*3
print("Array-1")
print(x)
print("Array-2")
print(y)
new_array = None
### start your implementation here ###
# new_array = ... 
### end your implementation here ###
print(new_array)


Original arrays:
Array-1
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array-2
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]

Stack arrays in sequence vertically:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


11. Write a NumPy program to extract first, third and fifth elements of the third and fifth rows from a given (6x6) array.

In [6]:
arra_data = np.arange(0,36).reshape((6, 6))
print("Original array:")
print(arra_data)
print("\nExtracted data: First, third and fifth elements of the third and fifth rows")

### start your implementation here ###
# print(array_data[...]) 
### end your implementation here ###

Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Extracted data: First, third and fifth elements of the third and fifth rows
[[12 14 16]
 [24 26 28]]


12. Write a NumPy program to check whether a Numpy array contains a specified row.

In [14]:
num = np.arange(20)
arr1 = np.reshape(num, [4, 5])
print("Original array:")
print(arr1)
### start your implementation here ###
# print(...) #check if [0, 1, 2, 3, 4] is in arr1
# print(...) #check if [0, 1, 2, 3, 5] is in arr1
# print(...) #check if [15, 16, 17, 18, 19] is in arr1
### end your implementation here ###

Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
True
False
True


13. Write a NumPy program to compute the multiplication of two given matrixes.

In [17]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)

result = None
### start your implementation here ###
# result = ...
### end your implementation here ###
print("\nResult of the said matrix multiplication:")
print(result)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]

Result of the said matrix multiplication:
[[1 2]
 [3 4]]


14. Write a NumPy program to compute the outer product of two given vectors.

In [18]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)

result = None
### start your implementation here ###
# result = ...
### end your implementation here ###
print("\nOuter product of the said two vectors:")
print(result)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]

Outer product of the said two vectors:
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


15. Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [20]:
np.random.seed(123)
x = np.random.random((5,5))
print("Original Array:")
print(x) 

xmin, xmax = None, None
### start your implementation here ###
# xmin, xmax = ...
### end your implementation here ###
print("\nMinimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.6965 0.2861 0.2269 0.5513 0.7195]
 [0.4231 0.9808 0.6848 0.4809 0.3921]
 [0.3432 0.729  0.4386 0.0597 0.398 ]
 [0.738  0.1825 0.1755 0.5316 0.5318]
 [0.6344 0.8494 0.7245 0.611  0.7224]]

Minimum and Maximum Values:
0.05967789660956835 0.9807641983846155


16. Write a NumPy program to normalize a 3x3 random matrix following `x = (x - min)/(max - min)`.

In [22]:
np.random.seed(123)
x = np.random.random((3,3))
print("Original Array:")
print(x)
### start your implementation here ###
# x = ...
### end your implementation here ###
print("\nAfter normalization:")
print(x)

Original Array:
[[0.6965 0.2861 0.2269]
 [0.5513 0.7195 0.4231]
 [0.9808 0.6848 0.4809]]

After normalization:
[[0.6229 0.0786 0.    ]
 [0.4304 0.6534 0.2603]
 [1.     0.6075 0.337 ]]


17. Write a NumPy program to find the nearest value from a given value(4) in an array.

In [26]:
np.random.seed(123)
x = np.random.uniform(1, 12, 5)
v = 4
n = None
### start your implementation here ###
# n = ...
### end your implementation here ###
print(n)

4.147532684454174


18. Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.

In [28]:
np.random.seed(123)
x = np.random.random(15)
print("Original array:")
print(x)

### start your implementation here ###
# x[...] = ...
### end your implementation here ###
print("\nMaximum value replaced by -1:")
print(x)

Original array:
[0.6965 0.2861 0.2269 0.5513 0.7195 0.4231 0.9808 0.6848 0.4809 0.3921
 0.3432 0.729  0.4386 0.0597 0.398 ]

Maximum value replaced by -1:
[ 0.6965  0.2861  0.2269  0.5513  0.7195  0.4231 -1.      0.6848  0.4809
  0.3921  0.3432  0.729   0.4386  0.0597  0.398 ]


19. Write a NumPy program to get the n largest values of an array.

In [34]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
print("\nShuffled array:")
print(x)

n = 3
result = None
### start your implementation here ###
# result = ...
### end your implementation here ###
print (f"\n{n}-largest values: ", result)

Original array:
[0 1 2 3 4 5 6 7 8 9]

Shuffled array:
[3 6 9 8 0 4 2 1 7 5]

3-largest values:  [7 8 9]


20. Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.

In [3]:
x = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0])
print("Original array:")
### start your implementation here ###
# print(...)
### end your implementation here ###

print("\nFloor values of the above array elements:")
### start your implementation here ###
# print(...)
### end your implementation here ###

print("\nCeil values of the above array elements:")
### start your implementation here ###
# print(...)
### end your implementation here ###

print("\nTruncated values of the above array elements:")
### start your implementation here ###
# print(...)
### end your implementation here ###

Original array:
[-1.6 -1.5 -0.3  0.1  1.4  1.8  2. ]

Floor values of the above array elements:
[-2. -2. -1.  0.  1.  1.  2.]

Ceil values of the above array elements:
[-1. -1. -0.  1.  2.  2.  2.]

Truncated values of the above array elements:
[-1. -1. -0.  0.  1.  1.  2.]


21. Write a NumPy program to calculate the probabilities given the unnormalized logits (Refer to Deep Learning - Part I - Softmax Loss).

In [39]:
np.random.seed(123)
num_classes = 10
logits = np.random.rand(num_classes)

prob = None
### start your implementation here ###
# ...
# prob = ...
### end your implementation here ###

print(prob)
print(prob.sum()) # check if prob is summed up to 1.

[0.1137 0.0754 0.0711 0.0983 0.1163 0.0865 0.151  0.1123 0.0916 0.0838]
1.0


22. Write a NumPy program to calculate the probabilities given the unnormalized logits. Here, the array of logits is of 2 dimensions: `(num_samples x num_classes)`. Figure out the probabilities for each sample.

In [40]:
np.random.seed(123)

num_samples = 4
num_classes = 10

logits = np.random.rand(num_samples, num_classes) 
### start your implementation here ###
# ...
# prob = ...
### end your implementation here ###
print(prob)
print(prob.sum(1)) # check: for each sample, prob is summed up to 1.

[[0.1137 0.0754 0.0711 0.0983 0.1163 0.0865 0.151  0.1123 0.0916 0.0838]
 [0.0911 0.134  0.1002 0.0686 0.0962 0.1352 0.0776 0.077  0.11   0.11  ]
 [0.1079 0.1337 0.118  0.1054 0.1178 0.079  0.0821 0.0719 0.0767 0.1075]
 [0.0648 0.0912 0.091  0.0969 0.0905 0.0808 0.0906 0.1445 0.152  0.0977]]
[1. 1. 1. 1.]


23. Write a NumPy program to calculate the Softmax Loss given the unnormalized logits and the ground-truth labels of the samples. Here, the shape of logits is: `(num_samples x num_classes)` and the shape of GT labels is `(num_samples,)`, each of which is the corresponding label for that sample. Figure out the total Softmax Loss.

In [41]:
np.random.seed(123)

n_samples = 4
n_classes = 10

logits = np.random.rand(n_samples, n_classes)
labels = np.random.randint(0, 10, size=(n_samples,))

loss = None
### start your implementation here ###
# ...
# prob = ...
# loss = ...
### end your implementation here ###

print(loss)

9.617162525900268


24. Write a NumPy program to calculate the accuracy for classification. Given the output logits of the model (`num_samples x num_classes`) and the ground-truth labels of corresponding samples (`num_samples`,), calculate the accuracy of the classification result.

In [2]:
np.random.seed(123)

n_samples = 100
n_classes = 20

logits = np.random.randn(n_samples, n_classes)
labels = np.random.randint(0, n_classes, (n_samples,))

acc = None
### start your implementation here ###
# ...
# acc = ...
### end your implementation here ###

print(acc)

0.09


25. Write a NumPy program to calculate the precision, recall and f1-score for a binary-classification problem:

(1). Given the output of a model (`num_samples`,), calculate the probability of being class-1 by implementing a sigmoid function, i.e., $p(x=1)=sigmoid(output)$.

(2). Suppose we use a threshold $\tau=0.5$, and if $p(x)>\tau$, the model will predict the corresponding sample as class-1, else class-0.

(3). Compare the model predictions with the given ground-truth labels (`num_samples`,), and calculate the precision, recall of class-1.

In [3]:
n_samples = 100
thres = 0.5
r = 0.7
zeros = np.zeros(n_samples,)
one_indices = np.random.choice(n_samples, int(r*n_samples), replace=False)
zeros[one_indices] = 1

labels = np.copy(zeros)
outp = np.random.randn(n_samples,)

# sigmoid function
def sigmoid(x):
    pass # delete this line and implement the sigmoid function below
    ### start your implementation here ###
    # ...
    # return ...
    ### start your implementation here ###

p = sigmoid(outp)
### start your implementation here ###
# ...
# pred = ...  # those predicted to be class 1
### end your implementation here ###

# TP of class-1
tp = None
### start your implementation here ###
# tp = ... # true positive
### end your implementation here ###

# recall of class-1
recall = None
### your implementation here ###
# recall = ...
### your implementation here ###

# precision of class-1
prec = None
### start your implementation here ###
# prec = ...
### end your implementation here ###

print(f"recall of class-1: {recall}, precision of class-1:{prec}.")

recall of class-1: 0.4857142857142857, precision of class-1:0.6938775510204082.


26. Implement Convolution ($I$).


Recall the contents in the lecture, for a convolutional layer, an input tensor
and a kernel tensor are combined to produce an output tensor through a (**cross-correlation operation.**)

Let's ignore channels for now and see how this works with two-dimensional data and hidden representations.
In the following figure, the input is a two-dimensional tensor with a height of 3 and width of 3.
We mark the shape of the tensor as $3 \times 3$ or ($3$, $3$).
The height and width of the kernel are both 2.
The shape of the *kernel window* (or *convolution window*)
is given by the height and width of the kernel
(here it is $2 \times 2$).

![Two-dimensional cross-correlation operation. The shaded portions are the first output element as well as the input and kernel tensor elements used for the output computation: $0\times0+1\times1+3\times2+4\times3=19$.](./fig/correlation.svg)


In the two-dimensional cross-correlation operation,
we begin with the convolution window positioned
at the upper-left corner of the input tensor
and slide it across the input tensor,
both from left to right and top to bottom.
When the convolution window slides to a certain position,
the input subtensor contained in that window
and the kernel tensor are multiplied elementwise
and the resulting tensor is summed up
yielding a single scalar value.
This result gives the value of the output tensor
at the corresponding location.
Here, the output tensor has a height of 2 and width of 2
and the four elements are derived from
the two-dimensional cross-correlation operation:

$$
0\times0+1\times1+3\times2+4\times3=19,\\
1\times0+2\times1+4\times2+5\times3=25,\\
3\times0+4\times1+6\times2+7\times3=37,\\
4\times0+5\times1+7\times2+8\times3=43.
$$

Note that along each axis, the output size
is slightly smaller than the input size.
Because the kernel has width and height greater than one,
we can only properly compute the cross-correlation
for locations where the kernel fits wholly within the image,
the output size is given by the input size $n_h \times n_w$
minus the size of the convolution kernel $k_h \times k_w$
via

$$(n_h-k_h+1) \times (n_w-k_w+1).$$

This is the case since we need enough space
to "shift" the convolution kernel across the image
(We do not consider padding here).
Now, we implement this process in the `conv2d` function,
which accepts an input tensor `X` and a kernel tensor `K`
and returns an output tensor `Y`.

In [4]:
import torch
from torch import nn

def conv2d(X, K):
    """Compute 2D cross-correlation."""
    h, w = K.shape
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            pass # delete this line and implement the sigmoid function below 
            ### start your implementation here ###
            # Y[...] = 
            ### end your implementation here ###
    return Y

X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
K = torch.tensor([[0.0, 1.0], [2.0, 3.0]])
conv2d(X, K)

tensor([[19., 25.],
        [37., 43.]])

27. Implement Convolution ($II$).

(**Multiple Input and Multiple Output Channels**)
While we described the multiple channels that comprise each image (e.g., color images have the standard RGB channels
to indicate the amount of red, green and blue) and convolutional layers for multiple channels.
In `26`, we simplified all of our numerical examples by working with just a single input and a single output channel.
This allowed us to think of our inputs, convolution kernels, and outputs each as two-dimensional tensors.

When we add channels into the mix, our inputs and hidden representations both become three-dimensional tensors.
For example, each RGB input image has shape $3\times h\times w$.
We refer to this axis, with a size of 3, as the *channel* dimension. The notion of channels is as old as CNNs themselves.
Let's take a deeper look at convolution kernels with multiple input and multiple output channels.

**Multiple Input Channels**

When the input data contains multiple channels,
we need to construct a convolution kernel
with the same number of input channels as the input data,
so that it can perform cross-correlation with the input data.
Assuming that the number of channels for the input data is $c_i$,
the number of input channels of the convolution kernel also needs to be $c_i$. If our convolution kernel's window shape is $k_h\times k_w$,
then when $c_i=1$, we can think of our convolution kernel
as just a two-dimensional tensor of shape $k_h\times k_w$.

However, when $c_i>1$, we need a kernel
that contains a tensor of shape $k_h\times k_w$ for *every* input channel. Concatenating these $c_i$ tensors together
yields a convolution kernel of shape $c_i\times k_h\times k_w$.
Since the input and convolution kernel each have $c_i$ channels, we can perform a cross-correlation operation on the two-dimensional tensor of the input and the two-dimensional tensor of the convolution kernel for each channel, adding the $c_i$ results together (summing over the channels)
to yield a two-dimensional tensor.
This is the result of a two-dimensional cross-correlation between a multi-channel input and a multi-input-channel convolution kernel.

The below figure provides an example of a two-dimensional cross-correlation with two input channels.
The shaded portions are the first output element
as well as the input and kernel tensor elements used for the output computation:
$(1\times1+2\times2+4\times3+5\times4)+(0\times0+1\times1+3\times2+4\times3)=56$.

![Cross-correlation computation with 2 input channels.](./fig/conv-multi-in.svg)

To make sure we really understand what is going on here,
we can (**implement cross-correlation operations with multiple input channels**) ourselves.
Notice that all we are doing is performing a cross-correlation operation
per channel and then adding up the results.

In [44]:
def conv2d_multi_in(X, K):
    # Iterate through the 0th dimension (channel) of K first, then add them up
    ### start your implementation here ###
    res = None
    # res = ...  # use the conv2d function above
    ### end your implementation here ###
    return res

X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
               [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])

conv2d_multi_in(X, K)

tensor([[ 56.,  72.],
        [104., 120.]])

**Multiple Output Channels**

Regardless of the number of input channels, so far we always ended up with one output channel. However, as we discussed in the lecture,
it turns out to be essential to have multiple channels at each layer.

Denote by $c_i$ and $c_o$ the number of input and output channels, respectively,
and let $k_h$ and $k_w$ be the height and width of the kernel.
To get an output with multiple channels, we can create a kernel tensor
of shape $c_i\times k_h\times k_w$ for *every* output channel.
We concatenate them on the output channel dimension, so that the shape of the convolution kernel
is $c_o\times c_i\times k_h\times k_w$.
In cross-correlation operations, the result on each output channel is calculated
from the convolution kernel corresponding to that output channel and takes input from all channels in the input tensor.

Implement a cross-correlation function to [**calculate the output of multiple channels**] in the below cell.

In [45]:
def conv2d_multi_in_out(X, K):
    # Iterate through the 0th dimension of `K`, and each time, perform
    # cross-correlation operations with input `X`. All of the results are
    # stacked together

    ### start your implementation here ###
    res = None
    # res = ...  # use the conv2d_multi_in function above
    ### end your implementation here ###
    return res

K = torch.stack((K, K + 1, K + 2), 0)
print(K.shape)

print(conv2d_multi_in_out(X, K))



torch.Size([3, 2, 2, 2])
tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])


28. Maximum Pooling and Average Pooling.

Like convolutional layers, *pooling* operators consist of a fixed-shape window that is slid over
all regions in the input according to its stride, computing a single output for each location traversed by the fixed-shape window (sometimes known as the *pooling window*).
However, unlike the cross-correlation computation of the inputs and kernels in the convolutional layer, the pooling layer contains no parameters (there is no *kernel*).
Instead, pooling operators are deterministic, typically calculating either the maximum or the average value
of the elements in the pooling window.
These operations are called *maximum pooling* (*max-pooling* for short) and *average pooling*, respectively.

We can think of the pooling window as starting from the upper-left of the input tensor and sliding across the input tensor from left to right and top to bottom.
At each location that the pooling window hits, it computes the maximum or average value of the input subtensor in the window, depending on whether max or average pooling is employed.

![Max-pooling with a pooling window shape of $2\times 2$. The shaded portions are the first output element as well as the input tensor elements used for the output computation: $\max(0, 1, 3, 4)=4$.](./fig/pooling.svg)

The output tensor in the above  has a height of 2 and a width of 2.
The four elements are derived from the maximum value in each pooling window:

$$
\max(0, 1, 3, 4)=4,\\
\max(1, 2, 4, 5)=5,\\
\max(3, 4, 6, 7)=7,\\
\max(4, 5, 7, 8)=8.\\
$$

More generally, we can define a $p \times q$ pooling layer by aggregating over 
a region of said size. Returning to the problem of edge detection, 
we use the output of the convolutional layer
as input for $2\times 2$ max-pooling.
Denote by `X` the input of the convolutional layer input and `Y` the pooling layer output. 
Regardless of whether or not the values of `X[i, j]`, `X[i, j + 1]`, 
`X[i+1, j]` and `X[i+1, j + 1]` are different,
the pooling layer always outputs `Y[i, j] = 1`.
That is to say, using the $2\times 2$ max-pooling layer,
we can still detect if the pattern recognized by the convolutional layer
moves no more than one element in height or width.

In the code below, please (**implement the forward propagation
of the pooling layer**) in the `pool2d` function.

In [9]:
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                pass # delete this line and implement the code below
                ### start your implementation here ###
                # Y[...] = 
                ### end your implementation here ###
            elif mode == 'avg':
                pass # delete this line and implement the code below
                ### start your implementation here ###
                # Y[...] = 
                ### end your implementation here ###
    return Y

# verify max-pooling
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
print(pool2d(X, (2, 2)))

# verify average-pooling
print(pool2d(X, (2, 2), 'avg'))

tensor([[4., 5.],
        [7., 8.]])
tensor([[2., 3.],
        [5., 6.]])
